import os
import sys

import pandas as pd
import numpy as np
from itertools import combinations

from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

def run_deseq2(count_file):
    '''
    Run DESeq2 analysis with batch correction.

    Parameters:
    -----------
    count_file : str
        Path to a .countMatrix file generated by 03_countMatrix.py

    Returns:
    --------
    metadata : DataFrame
        A Pandas DataFrame containing the sample information. Used for
        pairwise comparisons later.
    dds : Fitted DESeq2 object
    '''
    # Import count matrix
    count_matrix = pd.read_csv(count_file,
                     index_col='peakRegions')
    count_matrix = count_matrix.astype(int)
    
    # Generate metadata for batch correction
    samples = list(count_matrix.columns)
    metadata = pd.DataFrame({'sample':samples,
                             'condition':[s.split('-')[1] for s in samples],
                             'batch':[s.split('-')[0] for s in samples]
                            }).set_index('sample')
    
    # Create DEseqDataSet and run DEseq2 normalization 
    # and dispersion estimations
    dds = DeseqDataSet(
        counts=count_matrix.T,
        metadata=metadata,
        design='~ batch + condition',
        refit_cooks=True
    )
    dds.deseq2()
    
    return metadata, dds

def get_diff_peaks(dds,
                   contrast,
                   alpha=0.05,
                   lfc_threshold=1):
    '''
    Get differential peaks for a specific contrast
    
    Parameters:
    -----------
    dds : DeseqDataSet
        Fitted DESeq2 object
    contrast : list
        Contrast specification [factor, test, reference]
        e.g., ['condition', 'wt', 'apo']
    alpha : float
        FDR threshold (default: 0.05)
    lfc_threshold : float
        Log2 fold-change threshold (default: 1.0)
    
    Returns:
    --------
    all_results : DataFrame
        DESeq2 results for all peaks for the specified comparison.
    significant_results : DataFrame
        DESeq2 results filtered by FDR and log2FC threshold
    '''
    stat_res = DeseqStats(dds, contrast=contrast, alpha=alpha)
    stat_res.summary()
    results = stat_res.results_df
    sig_results = results[
        (results['padj'] < alpha) &
        (abs(results['log2FoldChange']) > lfc_threshold)
        ].copy()

    return results, sig_results

def run_all_contrasts(dds,
                      metadata,
                      count_file,
                      dir_out,
                      alpha=0.05,
                      lfc_threshold=1):
    '''
    Runs all pairwise combinations on a DESeq2 analysis and export
    the differential peaks.

    Parameters:
    -----------
    dds : DeseqDataSet
        First output of run_deseq2()
    metadata : DataFrame
        Second output of run_deseq2()
    count_file : str
        Path to .countMatrix used by run_deseq2()
    dir_out : str
        Directory for differential peak files.

    Returns:
    --------
    get_diff_peaks() output for every pairwise condition combination.
    ''' 
    # Get outfile prefix
    prefix = os.path.basename(count_file)
    prefix = prefix.replace('consensusPeaks.countMatrix','')
    prefix = os.path.join(dir_out,prefix)
    
    contrasts = list(combinations(sorted(set(metadata['condition'])),2))

    for a, b in contrasts:
        contrast = ['condition', a, b]
        results, sig_results = get_diff_peaks(dds,
                                              contrast,
                                              alpha,
                                              lfc_threshold)
        res_name = f'{prefix}{a}-vs-{b}.allPeaks'
        sig_name = f'{prefix}{a}-vs-{b}.fdr{alpha}.lfc{lfc_threshold}.diffPeaks'
        results.to_csv(res_name)
        sig_results.to_csv(sig_name)

    return None
        
if __name__ == '__main__':
    args = sys.argv
    if len(args) == 5:
        # Import args
        count_file = args[1]
        alpha = float(args[2])
        lfc_threshold = float(args[3])
        dir_out = args[4]

        # Run DESeq2
        metadata, dds = run_deseq2(count_file)

        # Run contrasts
        run_all_contrasts(dds,
                          metadata,
                          count_file,
                          dir_out,
                          alpha,
                          lfc_threshold)
    else:
        print("Usage: 04_deseq2.py <count_file> <alpha> <lfc_threshold> <dir_out>", file=sys.stderr)
        sys.exit(1)
